### ISSUE TITLE
Enable external Postgres and Redis hosting (URL Override) on docker image

### ISSUE THREAD

**Issue by ricxsar** [SFDO-Tooling/MetaCI#1007]
We would like to host MetaCI to AWS instead of Heroku however I can't find any documentation on how to override the Postgres and Redis URL.

We're able to replicate the docker hosting (Heroku) on AWS ECS but it still referencing local Postgres and Redis which results in an error.

We are hosting Postgres on AWS RDS and Redis on AWS ElastiCache. Hoping you will take action on the request.

Thanks!

**Comment by davisagli** [comment]
Set the DATABASE_URL environment variable to control where MetaCI connects to the database, and the REDIS_URL for the redis connection. DATABASE_URL is parsed using [dj-database-url](https://pypi.org/project/dj-database-url/) into Django database settings, and REDIS_URL is used to build the LOCATION setting for django-redis: https://github.com/SFDO-Tooling/MetaCI/blob/master/config/settings/production.py#L171

Note that we built the Docker image to support local development. We aren't using it for production yet and it may need some changes to be suitable for production.

And I think you are the first to try running MetaCI on a different platform than Heroku, so you may discover other limitations as well. In particular, the support for auto-scaling the number of workers is built for Heroku.

**Comment by ricxsar** [comment]
> the support for auto-scaling the number of workers is built for Heroku.
Oh, I see. That will cause a problem then.

If that's the case, is it possible for me to override the Heroku `app.json` file to remove the addons (Postgres and Redis) and add additional environment variables `DATABASE_URL` `REDIS_URL`and  to point them externally?

If so, better if you can add additional `Deploy to Heroku` button with the above use case?

**Comment by davisagli** [comment]
app.json and the Deploy to Heroku button are intended to provide a shortcut for setting up the simplest, most common configuration. If your needs are different you can set up the app manually instead:
1. Create the app from Heroku dashboard.
2. Add the necessary config vars and buildpacks
3. Add the necessary addons, or set config vars to point to external data stores instead
4. Deploy this repository
5. Scale the different dyno types on the app's Resources tab.

**Comment by ricxsar** [comment]
@davisagli Okay, I undertand. One more question:
Can you explain the difference among formations? What does it do and the recommendations on their scaling configuration in terms of how many builds can be accommodated?
```
"formation": {
    "web": {
      "quantity": 1,
      "size": "free"
    },
    "dev_worker": {
      "quantity": 1,
      "size": "free"
    },
    "worker": {
      "quantity": 0,
      "size": "free"
    },
    "worker_short": {
      "quantity": 0,
      "size": "free"
    }
  },
```

**Comment by davisagli** [comment]
@ricxsar There are 4 processes which need to run as part of MetaCI:
1. web dyno to serve HTTP requests
2. rqworker for the short queue to handle tasks that don't take much time, like checking if there are builds to queue
3. rqworker for the other queues (high/medium/default) which actually run builds
4. rqscheduler to add tasks to the short queue on a regular schedule

If you're trying to run with the cheapest configuration possible, you can run 1 web dyno and 1 dev_worker dyno. The dev_worker dyno runs one of each of the rq processes. You'll be able to run one build at a time.

If you want to run multiple builds in parallel, then you'll need:
- at least 1 web dyno
- exactly 1 worker_short dyno (which runs 2 rqworkers processing the short queue and 1 rqscheduler)
- at least 1 worker dyno (and probably set up autoscaling to add more when there is demand)

**Comment by ricxsar** [comment]
@davisagli Thanks. It was very helpful. I will close the issue now. More power to you.
