### ISSUE TITLE
Integrate django-meta

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#103]
Currently links to builds in mrbelvedereci don't show up in other apps with good information.  We should integrate django-meta to show a better build summary with a build url.  For example, when a build url is posted in Quip chat, it should show a nicer summary with information about the actual build

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL9JAAW" target="_blank">W-022293</a>
