### ISSUE TITLE
Lock builds to prevent rebuilds

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/MetaCI#106]
Sometimes a build could technically be rebuilt but we may want to prevent that. We should add some concept of locking a build so that further rebuilds are not possible.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL9IAAW" target="_blank">W-022292</a>
