### ISSUE TITLE
Add Restricted option to Plan

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#108]
Add a new boolean field, restricted, to Plan that limits running and rebuilding a particular plan to only superusers.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL9HAAW" target="_blank">W-022291</a>

**Comment by davisagli** [comment]
We solved this a different way using django-guardian
