### ISSUE TITLE
Allow for disabling a Plan Schedule

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#132]
The PlanSchedule model should have an `active` field that behaves like `Plan.active`.  The field should be checked by default.  If unchecked, the schedule would not run at its interval.  Currently, the only way to disable a schedule is to delete it which also deletes the associated builds.

**Comment by davisagli** [comment]
The PlanSchedule model was removed, so I guess that also accomplished disabling it ;-)
