### ISSUE TITLE
JWT Auth Resetting instance_url for Sandbox Persistent Orgs

### ISSUE THREAD

**Issue by banderson5144** [SFDO-Tooling/MetaCI#1497]
When flow is ran against a persistent sandbox org, it re-writes the `instance_url` from `https://test.salesforce.com` to the my domain of the sandbox. This then causes a JWT Audience error since it only accepts `https://test.salesforce.com`

**Comment by davisagli** [comment]
@banderson5144 We merged https://github.com/SFDO-Tooling/MetaCI/pull/1516 which I think will fix this.

In the org config, `instance_url` should be set to the org's My Domain. The JWT `aud` value will now be based on the `id` from the org config, which should start with https://test.salesforce.com for a sandbox.
