### ISSUE TITLE
Track which task was running when a failure occurs

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#172]
Currently the build shows the exception information but doesn't clearly tell you where in the flow the exception was raised.  It would be helpful to also show which task the exception came from on the Overview page.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8WAAW" target="_blank">W-022290</a>
