### ISSUE TITLE
Private repos are visible in plan detail view and build detail view

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/MetaCI#179]
At least these 2 views show private repo info when they shouldn't.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8VAAW" target="_blank">W-022289</a>

**Comment by davisagli** [comment]
This appears to be working correctly since the access control refactoring.
