### ISSUE TITLE
keychain should use sfdx commands to retrieve org data 

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/MetaCI#180]
instead of the disable encryption option

WARNING: The environment variable "SFDX_DISABLE_ENCRYPTION" has been deprecated and will be removed in v42.0 or later. Use "sfdx force:auth to re-authorize your orgs" instead.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8UAAW" target="_blank">W-022288</a>
