### ISSUE TITLE
@staff_member_required redirects to admin login

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/MetaCI#229]
the @staff_member_required decorator we use on many of our views redirects to the DJ admin login page instead of social auth.

**Comment by davisagli** [comment]
Since we switched from this decorator to permission checks, now users get a bare 403 Forbidden which is also not ideal. What we probably want is a prompt to start oauth that will end up returning to the url they were trying to access.

**Comment by davisagli** [comment]
duplicate of #282
