### ISSUE TITLE
Record aggregate results on TestMethod

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#24]
Whenever we write a new TestResult, we should update aggregate values on the TestMethod it points to.  Example aggregate values include:

* build_count_7days
* build_count_30days
* build_count_90days
* pass_percent_7days
* pass_percent_30days
* pass_percent_90days

**Comment by jlantz** [comment]
Actually, if we were using a rolling time window, we'd need to run a nightly job too to keep these updated

**Comment by davisagli** [comment]
I think Paul's approach on the performance dashboard makes this unnecessary.
