### ISSUE TITLE
Login form misleading

### ISSUE THREAD

**Issue by annejackson** [SFDO-Tooling/MetaCI#282]
Sometimes I end up on this page when I see I'm logged out of metaCI and trying to get back in- see below link and screenshot (either when in my profile page and my session has timed-out, or trying to use new org please):
https://mrbelvedereci.herokuapp.com/accounts/login/

<img width="1440" alt="login form misleading" src="https://user-images.githubusercontent.com/35311289/44543181-d7e62400-a6dc-11e8-8f1f-c70162e75013.png">

**Sometimes I get redirected to this login page that looks like it's for an admin and not me, which is also confusing (screenshot below):
https://mrbelvedereci.herokuapp.com/admin-nhPbfE4vOzFBhy2S/login/?next=/plans/new_org_please/
![login_dijango](https://user-images.githubusercontent.com/35311289/44543512-bd607a80-a6dd-11e8-9125-bef681c09eda.png)

As a user, the normal is to fill out username and password fields as they stand out, However, I don't believe we need these fields as you login through Github link anyways. 

so my suggestion would be to remove the login fields if we don't need them and make the Github link stand out a little more AND to not redirect users to the dijango administration login page. Also, make sure that after a user selects the github link what page should it go to? Their profile page? A home page on metaci? Or the page they were trying to go to when they got the error- like the https://mrbelvedereci.herokuapp.com/plans/new_org_please/

**Comment by annejackson** [comment]
here you go @cdcarter

**Comment by annejackson** [comment]
Update:
Now if this happens they don't get the Django admin screen, you just get a 403 Forbidden message with no feedback on what you need to do.

**Comment by Julian88Tex** [comment]
Almost created a new issue until I saw this one.

**Comment by Julian88Tex** [comment]
@davisagli Curious if there is any priority and/or issues with implementing this one. Would love to have this one implemented since I get questions about it on a monthly basis usually in the form of "I cannot see your link".

**Comment by davisagli** [comment]
@Julian88Tex This fell off my radar but I don't think it will be super difficult. @Br4nd0R is going to pick it up next month.

**Comment by davisagli** [comment]
@annejackson @Julian88Tex fix for this should be deployed Thursday night.

**Comment by annejackson** [comment]
Wahoo!

**Comment by Julian88Tex** [comment]
Excited :-)
