### ISSUE TITLE
Creation and Profile Page: Have the ability to add notes to a scratch org

### ISSUE THREAD

**Issue by annejackson** [SFDO-Tooling/MetaCI#319]
This is similar to some other suggestions. 

There are times when I create an org using exactly the same project, plan and flow. So in the profile page the orgs are listed and look the same and I can't tell which org contains which testing data, which testing purpose, etc. 

**A use case:**
I need to create two orgs with same project, plan and flow in Cumulus, however one org is strictly for multi currency testing, and the other org is for non multi currency testing. 

It would be nice to have a Notes field on creation where I can specify what the purpose of the scratch org is for. Then, that notes field would be listed on the profile page for the list of my current scratch orgs.

Bonus feature: If I could edit the notes field on the profile page in case the org purpose changes.

See screenshot with notes below. 
![metaci scratch org list request](https://user-images.githubusercontent.com/35311289/47925189-ec405d00-de93-11e8-9a4f-2c0cf517823e.png)

**Comment by annejackson** [comment]
fyi @cdcarter and @jlantz

**Comment by davisagli** [comment]
see also #233

**Comment by davisagli** [comment]
@annejackson @melissabarber thanks to @Br4nd0R, you can now enter an Org Note when creating a scratch org in MetaCI.
