### ISSUE TITLE
Running and Managing Builds MetaCI, Builds goes in queue

### ISSUE THREAD

**Issue by addys888** [SFDO-Tooling/MetaCI#343]
Hi,
We are creating a build using MetaCI plans command (`metaci plan run <PlanID>`). But all the builds we are creating goes into 'Queued' build status. We weren't able to find why our all builds come into queued status.

![plan and build list_modified](https://user-images.githubusercontent.com/25403058/50289609-5dad8c80-048f-11e9-91dc-d39818e232f9.png)

Please let us know if we are doing anything wrong in above-mentioned steps or there are any additional configurations that we need to make.

Thanks,

**Comment by davisagli** [comment]
It's normal for them to start as queued and then they should be picked up by the worker dynos. Check the logs for your worker dyno(s) for errors.

**Comment by addys888** [comment]
Thanks for your response. I would like to know is there any way to destroy or delete all pending 'queued' metaci builds.

**Comment by davisagli** [comment]
Yes, if you go to the URL /django-rq/ you will see a list of queues. Click on the name of a queue (`default` is the one used for builds) and then the Empty Queue button at upper right.
