### ISSUE TITLE
Repo/plan privacy

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/MetaCI#46]
Currently we can set "public" on each build plan.

Build plans should inherit privacy settings from the repo, and repos should query privacy setting from the github api. This way it is all automatic and will match what is in github.

With this change should be a recurring background job to scan all repositories for changes in privacy status.

**Comment by davisagli** [comment]
We implemented per-planrepo permission control using django-guardian rather than based on github ACLs.
