### ISSUE TITLE
Bad request when attempting to access settings/config

### ISSUE THREAD

**Issue by kbromer** [SFDO-Tooling/MetaCI#460]
![Screen Shot 2019-07-13 at 1 54 57 PM](https://user-images.githubusercontent.com/926530/61174986-eac44a00-a575-11e9-9e53-65a3b47d863b.png)

**Comment by davisagli** [comment]
Working as designed — the admin UI is restricted to the corporate network.

**Comment by kbromer** [comment]
Ah, VPN must've dropped, ty sir
