### ISSUE TITLE
When creating a notification, the list of branches includes every branch that ever had a build against it

### ISSUE THREAD

**Issue by force2b** [SFDO-Tooling/MetaCI#542]
When I try to add a notification from a specific branch at https://mrbelvedereci.herokuapp.com/notifications/ I'm seeing a list of branches that includes branches that were deleted years ago, such as feature/crlp-ocr-fix. There are hundreds more like that.

Is there a reason this page has to list every single branch that ever existed rather than jut the current branches that currently exist (or maybe branches that have had builds in the last 30 days)? This giant causes two issues.

1. The page times out on the first load
2. It's really challenging to find the actual branch I want to create a notification for

Implementing #28 would probably help with the 2nd point, but not the the first.

**Comment by davisagli** [comment]
@force2b I adjusted this page to avoid making one query per branch to get the repository name, which resolved the performance problem. And now that I can actually load the page, I don't see deleted branches -- I'm not sure if that's a side effect of how I fixed the performance, or if I'm missing some step to reproduce that.

**Comment by force2b** [comment]
Thanks @davisagli. I confirm that the list of branches is now significantly smaller. Thank you very much for fixing this!!
