### ISSUE TITLE
Track deleted branches

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#80]
When the push webhook contains a current HEAD commit sha of 000000* it's an indicator that the branch has been deleted.  We currently ignore these webhook events but should probably instead use them to mark branches as deleted.  We would also need to handle a branch that was deleted getting recreated

**Comment by cpolcyn** [comment]
Related to https://github.com/SalesforceFoundation/mrbelvedereci/issues/54

duplicate?

**Comment by cdcarter** [comment]
lets inherit from SoftDeletableModel from django_model_utils

**Comment by cpolcyn** [comment]
addressed in https://github.com/SalesforceFoundation/MetaCI/pull/214

**Comment by cpolcyn** [comment]
This is a bit different than the implementation in https://github.com/SalesforceFoundation/MetaCI/pull/214 so I will re-open.
