### ISSUE TITLE
Feature: Allow builds to report their status accurately

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/MetaCI#815]
A job could run once every 5 minutes to try and correlate worker IDs to build IDs.

Builds could store their worker in their model. (set_build_info method is a good place for this)

If a Build is associated with a worker that been assigned to another build, then the build is an orphan and therefore can be marked as ERROR.

If the worker associated with the build does not exist anymore, then the build is also an orphan.

**Comment by davisagli** [comment]
/django-rq usually seems to be pretty accurate about what jobs are running. So another possibility would be to record the job id (oh look, we [already do](https://github.com/SFDO-Tooling/MetaCI/blob/master/metaci/build/tasks.py#L85)) and then check redis periodically for whether it's still active

**Comment by prescod** [comment]
How does /django-rq detect if a worker has gone AWOL?

**Comment by davisagli** [comment]
@prescod was this primarily about builds that showed a status of running even though their worker had died? If so then I think it is much less of a problem since we deployed #1067.

**Comment by prescod** [comment]
Yes, that was the main use-case.
