### ISSUE TITLE
Scratch Org URL Callback error

### ISSUE THREAD

**Issue by cidarm** [SFDO-Tooling/MetaCI#868]
I am running into the following error when creating a scratch org:

**ERROR running force:org:create:  The callback URL provided is not valid**

CCI can successfully spin up a scratch on my local repo with the URL displayed in the connected_app, which is:  http://localhost:8080/callback

Is there another URL that needs to be configured?   Please advise.

Thanks,
Cid

**Comment by Br4nd0R** [comment]
Hi Cid,

Have you setup a connected app via `cci task run connected_app` or `cci service connect connected_app` yet?

If not, here are [the docs](https://cumulusci.readthedocs.io/en/latest/tutorial.html#creating-a-connected-app) for setting up and connecting to a connected app.

If you have attempted these steps, are you using the Salesforce Connected App or one that you created yourself?

**Comment by cidarm** [comment]
I had multiple cci projects running on my local machine so once I made sure to set my variables to the cci project itself MetaCi was good to go.  

DevHub `cci service connect devhub --project`
Connected_App `cci service  connect connected_app --project `
Git command to remove the default org setup on the sfdx project files. `git rm -rf .sfdx`
